#seqlist.out:seqlist.cpp
#	g++ -o seqlist.out seqlist.cpp -g
#PHONY:clean
#clean:
#	rm -rf seqlist.out
read_write.out:read_write.c
	gcc -o read_write.out read_write.c
PHONY:clean
clean:
	rm -rf read_write.out
