#mask.out:mask.c
#	gcc -o mask.out mask.c
#PHONY:clean
#clean:
#	rm -rf mask.out
#sighandler:sighandler.c
#	gcc -o $@ $^
#PHONY:clean
#clean:
#	rm -rf sighandler
#sleep:sleep.c
#	gcc -o $@ $^
#PHONY:clean
#clean:
#	rm -rf sleep
ke_chong_ru:ke_chong_ru.c
	gcc -o $@ $^ -O3  #优化方案有三种 -O1 -O2 -O3 ,其中-O3优化等级最高
PHONY:clean
clean:
	rm -rf ke_chong_ru 

